### ISSUE TITLE
Sharex

### ISSUE THREAD

**Issue by Kadantte** [Spimy/cdn.spimy.dev#1]
Hello, I love the idea of having your personal `cdn` it would be great if it could upload files via Sharex!

**Comment by Spimy** [comment]
You already can. The custom uploader just has to be set-up like the following:
![image](https://user-images.githubusercontent.com/34989646/217247030-4871b958-6c8c-41ca-9a1f-a9fc7799da50.png)

Just change the URL to whatever domain you own when you host it on a web server. Do note that I have not yet implemented any form of authentication so anyone will be able to upload to your server if people know the URL.

**Comment by Spimy** [comment]
Update: added a very basic authentication.

New custom uploader settings should look like so:
![image](https://user-images.githubusercontent.com/34989646/217261645-cd97c97b-7022-42d6-bede-a99d4f76f695.png)

Generate a random hash using: https://passwordsgenerator.net/sha256-hash-generator/

**Comment by Kadantte** [comment]
Thanks, adding authentication should prevent anyone from trying to upload files from their end!
